### ISSUE TITLE
Overlay heatmap with full-field image

### ISSUE THREAD

**Issue by nheyek** [terraref/traitvis-webapp#10]
Combine full field images (available on terraref workbench) with heat map trait visualization.

**Comment by dlebauer** [comment]
it should be possible to add these here: https://github.com/terraref/traitvis-webapp/blob/master/render-site-map.R#L18

**Comment by dlebauer** [comment]
* You should be able to find a thumbnail for a given date in the path /data/terraref/sites/ua-mac/Level_1/fullfield/<YYYY-MM-DD>
* display these under the plots
* add either 
   * selection to go from filled to empty polygons (just showing borders) or
   * a slider to adjust alpha level so that the plots can be disappeared


* Might need to use even smaller thumbnails to make this fast enough over internet (Max can help with that)
* The date selector should only stop at dates on which data was collected
* if there is more than one scan per day, take the first.

**Comment by kimberlyh66** [comment]
@dlebauer Is there another way to access the field images other than in workbench? I am having problems with running RStudio in workbench.

**Comment by dlebauer** [comment]
You can use clowder or globus to download a subset to start working with.

_______________________
David LeBauer
Director of Data Sciences
Arizona Experiment Station
THE UNIVERSITY OF ARIZONA

Bioscience Research Labs, 207
1230 N Cherry Ave | Tucson, AZ 85721
Office: 520-621-4381
dlebauer@email.arizona.edu

(sent from my phone - please pardon brevity and typos)


________________________________

**Comment by KristinaRiemer** [comment]
The tasks in David's first comment are completed.
