### ISSUE TITLE
investigate url parameter support

### ISSUE THREAD

**Issue by tcnichol** [terraref/traitvis-webapp#28]
We would like to use traitvis-webapp as the visualization for search results from the advanced search interface. In order for this to work, the shiny app needs to support url parameters for season, trait, etc.

**Comment by Chris-Schnaufer** [comment]
Direction is to go from traitvis-webapp to search

**Comment by dlebauer** [comment]
we have decided is that we will provide links / urls to the advanced search app from traitvis rather than vice-versa. Both ways would be nice but on a call it sounded like it will be much easier to provide urls to traitvis users to get to search rather than configure traitvis to have endpoints that can get from the search interface to the traitvis.

**Comment by dlebauer** [comment]
see #36 for implementing the reverse action

**Comment by dlebauer** [comment]
@kimberlyh66 please review https://www.r-bloggers.com/official-release-of-shiny-router-and-its-new-features/amp/ and comment on whether it will be possible to parameterize the traitvis webapp to open to either a map or a timeseries plot for a particular season, experiment, and variable

**Comment by kimberlyh66** [comment]
Would allowing users to open to a map like this be something you are looking for?

The url would be probably be something like: 


<img width="1430" alt="shiny-map-param-github-post-image" src="https://user-images.githubusercontent.com/44081116/62403076-c1c52280-b53f-11e9-89a4-fb44bc359e55.png">

**Comment by dlebauer** [comment]
Looks promising! Can the map and plot tabs be combined?

**Comment by kimberlyh66** [comment]
The plot can be displayed below the map.
